#!/bin/sh /etc/rc.common
START=99
STOP=01
USE_PROCD=1

start_service() {
    local level
    level="$(uci -q get landscape.container.log_level)"
    procd_open_instance
    procd_set_param command /usr/bin/redirect_pkg_handler --mode route \
        --sock_path /ld_unix_link --log-level "${level:-INFO}"
    procd_set_param respawn 3600 5 0
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param limits memlock="unlimited unlimited"
    procd_close_instance
}
