#!/bin/sh
set -eu
# New generation only: initialize once, then leave LuCI/PassWall DNS untouched.
[ "$(uci -q get landscape.container.initialized || true)" != 1 ] || exit 0
uci set 'dhcp.@dnsmasq[0].noresolv=1'
uci set 'dhcp.@dnsmasq[0].localservice=0'
uci -q delete 'dhcp.@dnsmasq[0].server' || true
uci add_list "dhcp.@dnsmasq[0].server=$(uci get landscape.container.dns)"
uci commit dhcp
uci set landscape.container.initialized=1
uci commit landscape
