#!/bin/sh
set -eu
# Initialize resolver-file use once; forwarding rules belong to LuCI/PassWall.
[ "$(uci -q get landscape.container.initialized || true)" != 1 ] || exit 0
uci set 'dhcp.@dnsmasq[0].noresolv=0'
uci set 'dhcp.@dnsmasq[0].resolvfile=/tmp/resolv.conf.d/resolv.conf.auto'
uci set 'dhcp.@dnsmasq[0].localservice=0'
uci commit dhcp
uci set landscape.container.initialized=1
uci commit landscape
